"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getCurrentAdmin } from "@/lib/admin";
import { getSupabaseAdmin } from "@/lib/supabase-admin";
import { createSupabaseServerClient } from "@/lib/supabase-server";

// =============================================================================
// ADMIN SERVER ACTIONS
// =============================================================================
// Every action below re-checks the admin allow list before doing anything.
// Never rely only on the middleware or on a hidden button: a determined visitor
// could POST directly to an action, so the permission check must live here too.
// =============================================================================

const IMAGE_BUCKET = "product-images";
const MAX_IMAGE_BYTES = 5 * 1024 * 1024; // 5 MB
const ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp", "image/avif"];

async function requireAdminAction() {
  const admin = await getCurrentAdmin();
  if (!admin) throw new Error("You are not authorised to do that.");
  return admin;
}

function text(formData: FormData, key: string, maxLength = 500) {
  const value = formData.get(key);
  return typeof value === "string" ? value.trim().slice(0, maxLength) : "";
}

function checked(formData: FormData, key: string) {
  return formData.get(key) === "on" || formData.get(key) === "true";
}

function numberValue(formData: FormData, key: string, fallback = 0) {
  const parsed = Number(text(formData, key, 20));
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : fallback;
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

// Splits "S, M, L" into ["S","M","L"], removes blanks and duplicates.
function parseSizes(value: string) {
  const seen = new Set<string>();
  return value
    .split(",")
    .map((size) => size.trim().slice(0, 20))
    .filter((size) => {
      if (!size) return false;
      const key = size.toLowerCase();
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
}

export async function signIn(formData: FormData) {
  const email = text(formData, "email", 200);
  const password = text(formData, "password", 200);

  const supabase = await createSupabaseServerClient();
  if (!supabase) redirect("/admin/login?error=not_configured");

  const { error } = await supabase.auth.signInWithPassword({ email, password });

  if (error) redirect("/admin/login?error=invalid");

  // Signing in is not enough. The account must also be on the staff allow list.
  // If it is not, we sign it straight back out again.
  const admin = await getCurrentAdmin();

  if (!admin) {
    await supabase.auth.signOut();
    redirect("/admin/login?error=not_allowed");
  }

  redirect("/admin");
}

export async function signOut() {
  const supabase = await createSupabaseServerClient();
  await supabase?.auth.signOut();
  redirect("/admin/login");
}
// Uploads a product photo and returns its public web address.
// The filename is generated by us, so a visitor cannot smuggle a dangerous
// filename or a script file into the storage bucket.
async function uploadImage(
  supabase: NonNullable<ReturnType<typeof getSupabaseAdmin>>,
  file: File,
  slug: string
) {
  if (!ALLOWED_IMAGE_TYPES.includes(file.type)) {
    throw new Error("Please upload a JPG, PNG, WEBP or AVIF image.");
  }

  if (file.size > MAX_IMAGE_BYTES) {
    throw new Error("That image is larger than 5 MB. Please choose a smaller photo.");
  }

  const extension =
    file.type === "image/png" ? "png" : file.type === "image/webp" ? "webp" : file.type === "image/avif" ? "avif" : "jpg";

  const path = slug + "-" + Date.now() + "." + extension;
  const bytes = new Uint8Array(await file.arrayBuffer());

  const { error } = await supabase.storage.from(IMAGE_BUCKET).upload(path, bytes, {
    contentType: file.type,
    upsert: false,
  });

  if (error) throw error;

  const { data } = supabase.storage.from(IMAGE_BUCKET).getPublicUrl(path);
  return data.publicUrl;
}

// The shop pages are cached, so they must be refreshed after an edit.
function revalidatePublicPages(slug?: string) {
  revalidatePath("/");
  revalidatePath("/shop");
  if (slug) revalidatePath("/products/" + slug);
}

async function replaceSizes(
  supabase: NonNullable<ReturnType<typeof getSupabaseAdmin>>,
  productId: string,
  sizes: string[],
  stockQuantity: number
) {
  await supabase.from("product_variants").delete().eq("product_id", productId).eq("variant_type", "size");

  if (sizes.length === 0) return;

  await supabase.from("product_variants").insert(
    sizes.map((size) => ({
      product_id: productId,
      variant_type: "size",
      variant_name: size,
      is_available: true,
      stock_quantity: stockQuantity,
    }))
  );
}

export async function createProduct(formData: FormData) {
  await requireAdminAction();

  const supabase = getSupabaseAdmin();
  if (!supabase) redirect("/admin/products?error=not_configured");

  const name = text(formData, "name", 120);
  const slug = slugify(text(formData, "slug", 80) || name);

  if (!name || !slug) redirect("/admin/products/new?error=missing_name");

  const stockQuantity = numberValue(formData, "stock_quantity");
  const sizes = parseSizes(text(formData, "sizes", 400));

  const { data: created, error } = await supabase
    .from("products")
    .insert({
      name,
      slug,
      category_id: text(formData, "category_id", 60) || null,
      short_description: text(formData, "short_description", 200) || null,
      description: text(formData, "description", 4000) || null,
      price: numberValue(formData, "price"),
      stock_quantity: stockQuantity,
      stock_status: stockQuantity > 0 ? "in_stock" : "out_of_stock",
      accent_color: text(formData, "accent_color", 20) || "#1769e0",
      badge: text(formData, "badge", 40) || null,
      is_featured: checked(formData, "is_featured"),
      is_published: checked(formData, "is_published"),
    })
    .select("id")
    .single();

  if (error) {
    console.error("Could not create product:", error);
    redirect("/admin/products/new?error=save_failed");
  }

  const productId = created.id;

  await replaceSizes(supabase, productId, sizes, stockQuantity);

  const image = formData.get("image");
  if (image instanceof File && image.size > 0) {
    try {
      const imageUrl = await uploadImage(supabase, image, slug);
      await supabase.from("product_images").insert({
        product_id: productId,
        image_url: imageUrl,
        alt_text: name,
        is_primary: true,
        sort_order: 0,
      });
    } catch (uploadError) {
      console.error("Image upload failed:", uploadError);
      revalidatePublicPages(slug);
      redirect("/admin/products/" + productId + "/edit?error=image_failed");
    }
  }

  revalidatePublicPages(slug);
  redirect("/admin/products?created=1");
}
export async function updateProduct(formData: FormData) {
  await requireAdminAction();

  const supabase = getSupabaseAdmin();
  if (!supabase) redirect("/admin/products?error=not_configured");

  const id = text(formData, "id", 60);
  const name = text(formData, "name", 120);
  const slug = slugify(text(formData, "slug", 80) || name);

  if (!id || !name || !slug) redirect("/admin/products?error=missing_name");

  const stockQuantity = numberValue(formData, "stock_quantity");
  const sizes = parseSizes(text(formData, "sizes", 400));

  const { error } = await supabase
    .from("products")
    .update({
      name,
      slug,
      category_id: text(formData, "category_id", 60) || null,
      short_description: text(formData, "short_description", 200) || null,
      description: text(formData, "description", 4000) || null,
      price: numberValue(formData, "price"),
      stock_quantity: stockQuantity,
      stock_status: stockQuantity > 0 ? "in_stock" : "out_of_stock",
      accent_color: text(formData, "accent_color", 20) || "#1769e0",
      badge: text(formData, "badge", 40) || null,
      is_featured: checked(formData, "is_featured"),
      is_published: checked(formData, "is_published"),
    })
    .eq("id", id);

  if (error) {
    console.error("Could not update product:", error);
    redirect("/admin/products/" + id + "/edit?error=save_failed");
  }

  await replaceSizes(supabase, id, sizes, stockQuantity);

  const image = formData.get("image");
  if (image instanceof File && image.size > 0) {
    try {
      const imageUrl = await uploadImage(supabase, image, slug);
      // A product has one main photo for now, so the old one is replaced.
      await supabase.from("product_images").delete().eq("product_id", id);
      await supabase.from("product_images").insert({
        product_id: id,
        image_url: imageUrl,
        alt_text: name,
        is_primary: true,
        sort_order: 0,
      });
    } catch (uploadError) {
      console.error("Image upload failed:", uploadError);
      revalidatePublicPages(slug);
      redirect("/admin/products/" + id + "/edit?error=image_failed");
    }
  }

  revalidatePublicPages(slug);
  redirect("/admin/products?updated=1");
}

export async function deleteProduct(formData: FormData) {
  await requireAdminAction();

  const supabase = getSupabaseAdmin();
  if (!supabase) redirect("/admin/products?error=not_configured");

  const id = text(formData, "id", 60);
  if (!id) redirect("/admin/products?error=missing_id");

  // Safe for history: order_items keep their own copy of the product name, size
  // and price, so deleting a product never damages past orders.
  const { error } = await supabase.from("products").delete().eq("id", id);

  if (error) {
    console.error("Could not delete product:", error);
    redirect("/admin/products?error=delete_failed");
  }

  revalidatePublicPages();
  redirect("/admin/products?deleted=1");
}

const ORDER_STATUSES = ["new", "confirmed", "preparing", "out_for_delivery", "completed", "cancelled"];

export async function updateOrderStatus(formData: FormData) {
  await requireAdminAction();

  const supabase = getSupabaseAdmin();
  if (!supabase) redirect("/admin/orders?error=not_configured");

  const id = text(formData, "id", 60);
  const status = text(formData, "status", 40);

  if (!id || !ORDER_STATUSES.includes(status)) {
    redirect("/admin/orders?error=invalid_status");
  }

  const { error } = await supabase.from("orders").update({ order_status: status }).eq("id", id);

  if (error) {
    console.error("Could not update order status:", error);
    redirect("/admin/orders/" + id + "?error=save_failed");
  }

  redirect("/admin/orders/" + id + "?updated=1");
}

export async function updateSettings(formData: FormData) {
  await requireAdminAction();

  const supabase = getSupabaseAdmin();
  if (!supabase) redirect("/admin/settings?error=not_configured");

  const { error } = await supabase
    .from("business_settings")
    .update({
      business_name: text(formData, "business_name", 120) || "Andres Sportsweartz",
      whatsapp_number: text(formData, "whatsapp_number", 30),
      phone_number: text(formData, "phone_number", 30) || null,
      email: text(formData, "email", 120) || null,
      currency: text(formData, "currency", 10) || "TZS",
      business_address: text(formData, "business_address", 200) || null,
      business_hours: text(formData, "business_hours", 200) || null,
      delivery_information: text(formData, "delivery_information", 500) || null,
      logo_url: text(formData, "logo_url", 300) || null,
      facebook_url: text(formData, "facebook_url", 300) || null,
      instagram_url: text(formData, "instagram_url", 300) || null,
      tiktok_url: text(formData, "tiktok_url", 300) || null,
    })
    .eq("id", 1);

  if (error) {
    console.error("Could not update settings:", error);
    redirect("/admin/settings?error=save_failed");
  }

  revalidatePath("/");
  revalidatePath("/shop");
  redirect("/admin/settings?saved=1");
}

function slugCode(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

const QR_SEGMENT_VALUES = ["general", "schools", "football", "whatsapp", "product", "custom"];

export async function createQrCampaign(formData: FormData) {
  await requireAdminAction();

  const supabase = getSupabaseAdmin();
  if (!supabase) redirect("/admin/qr?error=not_configured");

  const code = slugCode(text(formData, "code", 60));
  const name = text(formData, "name", 120);
  const rawSegment = text(formData, "segment", 20);
  const segment = QR_SEGMENT_VALUES.includes(rawSegment) ? rawSegment : "custom";
  const rawTarget = text(formData, "target_path", 200) || "/shop";
  const targetPath = rawTarget.startsWith("/") ? rawTarget : "/shop";
  const description = text(formData, "description", 300) || null;

  if (!code || !name) redirect("/admin/qr?error=invalid");

  // Auto-link product_<slug> codes to their product page for convenience.
  let productSlug: string | null = null;
  if (code.startsWith("product-")) {
    productSlug = code.slice("product-".length) || null;
  }

  const { error } = await supabase.from("qr_campaigns").insert({
    code,
    name,
    segment,
    target_path: targetPath,
    product_slug: productSlug,
    description,
    is_active: true,
  });

  if (error) {
    console.error("Could not create QR campaign:", error);
    redirect("/admin/qr?error=save_failed");
  }

  revalidatePath("/admin/qr");
  redirect("/admin/qr?created=1");
}

export async function toggleQrCampaign(formData: FormData) {
  await requireAdminAction();

  const supabase = getSupabaseAdmin();
  if (!supabase) redirect("/admin/qr?error=not_configured");

  const code = slugCode(text(formData, "code", 60));
  const isActive = text(formData, "is_active", 10) === "true";
  if (!code) redirect("/admin/qr?error=invalid");

  const { error } = await supabase.from("qr_campaigns").update({ is_active: isActive }).eq("code", code);

  if (error) {
    console.error("Could not update QR campaign:", error);
    redirect("/admin/qr?error=save_failed");
  }

  revalidatePath("/admin/qr");
  redirect("/admin/qr?updated=1");
}

export async function deleteQrCampaign(formData: FormData) {
  await requireAdminAction();

  const supabase = getSupabaseAdmin();
  if (!supabase) redirect("/admin/qr?error=not_configured");

  const code = slugCode(text(formData, "code", 60));
  if (!code) redirect("/admin/qr?error=invalid");

  const { error } = await supabase.from("qr_campaigns").delete().eq("code", code);

  if (error) {
    console.error("Could not delete QR campaign:", error);
    redirect("/admin/qr?error=save_failed");
  }

  revalidatePath("/admin/qr");
  redirect("/admin/qr?deleted=1");
}