import { NextResponse } from "next/server";
import { business } from "@/lib/business";
import { createLocalOrderReference, validateOrderPayload } from "@/lib/order-validation";
import { getPublishedProducts } from "@/lib/product-repository";
import { clientKeyFromRequest, rateLimit } from "@/lib/rate-limit";
import { getSupabaseAdmin, isDatabaseConfigured } from "@/lib/supabase-admin";

// =============================================================================
// POST /api/orders
// =============================================================================
// This is the ONLY place a customer order can be created.
//
// The browser sends product references, sizes and quantities. It is NEVER
// trusted. The server validates everything, looks up real prices itself, then
// writes the order using the secret service role key.
//
// Because the key stays on the server, a visitor cannot tamper with orders or
// read other customers' data.
// =============================================================================

// Basic abuse protection: a customer may submit 5 orders per 10 minutes.
const RATE_LIMIT_MAX_ORDERS = 5;
const RATE_LIMIT_WINDOW_MS = 10 * 60 * 1000;

export async function POST(request: Request) {
  const clientKey = clientKeyFromRequest(request);
  const limit = rateLimit("orders:" + clientKey, RATE_LIMIT_MAX_ORDERS, RATE_LIMIT_WINDOW_MS);

  if (!limit.allowed) {
    return NextResponse.json(
      {
        ok: false,
        message: "We have received several orders from this connection. Please wait a few minutes, or contact us on WhatsApp.",
      },
      { status: 429, headers: { "Retry-After": String(limit.retryAfterSeconds) } }
    );
  }

  let payload: unknown;
  try {
    payload = await request.json();
  } catch {
    return NextResponse.json(
      { ok: false, message: "The order details could not be read. Please try again." },
      { status: 400 }
    );
  }

  // Spam trap. This field is hidden from real customers, so if it contains
  // anything the request was almost certainly generated by a bot.
  if (payload && typeof payload === "object") {
    const trap = String((payload as Record<string, unknown>).website ?? "").trim();
    if (trap.length > 0) {
      return NextResponse.json(
        { ok: false, message: "Your order could not be submitted." },
        { status: 400 }
      );
    }
  }

  // The trusted catalogue. Prices and available sizes are read from here, never
  // from the browser request.
  const catalogue = await getPublishedProducts();
  const result = validateOrderPayload(payload, catalogue);

  if (!result.ok) {
    return NextResponse.json(
      {
        ok: false,
        message: "Please check the details below and try again.",
        errors: result.errors,
      },
      { status: 422 }
    );
  }

  const order = result.order;
  const supabase = isDatabaseConfigured ? getSupabaseAdmin() : null;

  // ---------------------------------------------------------------------------
  // CASE 1: Database not connected yet.
  // The order is still validated and priced correctly, and the customer is
  // asked to confirm it on WhatsApp. This lets the business trade on day one
  // before the database work is finished.
  // ---------------------------------------------------------------------------
  if (!supabase) {
    return NextResponse.json({
      ok: true,
      persisted: false,
      reference: createLocalOrderReference(),
      subtotal: order.subtotal,
      discountRate: order.discountRate,
      discountAmount: order.discountAmount,
      itemCount: order.itemCount,
      deliveryFee: order.deliveryFee,
      total: order.total,
      currency: order.currency,
      whatsappNumber: business.whatsappNumber,
      message:
        "Your order details are ready. Please send them to us on WhatsApp so we can confirm availability and delivery.",
    });
  }

  // ---------------------------------------------------------------------------
  // CASE 2: Database connected. Store the order permanently.
  // ---------------------------------------------------------------------------
  try {
    const { data: customer, error: customerError } = await supabase
      .from("customers")
      .upsert(
        { full_name: order.customerName, phone_number: order.phone },
        { onConflict: "phone_number" }
      )
      .select("id")
      .single();

    if (customerError) throw customerError;

    const { data: created, error: orderError } = await supabase
      .from("orders")
      .insert({
        customer_id: customer?.id ?? null,
        customer_name_snapshot: order.customerName,
        customer_phone_snapshot: order.phone,
        delivery_location: order.location,
        delivery_address: order.address,
        customer_notes: order.notes,
        campaign_code: order.campaignCode,
        item_count: order.itemCount,
        discount_rate: order.discountRate,
        discount_amount: order.discountAmount,
        subtotal: order.subtotal,
        delivery_fee: order.deliveryFee,
        total_amount: order.total,
        currency: order.currency,
      })
      .select("id, order_reference")
      .single();

    if (orderError) throw orderError;

    const { error: itemsError } = await supabase.from("order_items").insert(
      order.items.map((item) => ({
        order_id: created.id,
        // Becomes the real product id once products are moved into the database.
        product_id: null,
        product_name_snapshot: item.name,
        selected_size: item.size,
        quantity: item.quantity,
        unit_price: item.unitPrice,
        line_total: item.lineTotal,
      }))
    );

    if (itemsError) {
      // Never leave a half-saved order behind.
      await supabase.from("orders").delete().eq("id", created.id);
      throw itemsError;
    }

    return NextResponse.json({
      ok: true,
      persisted: true,
      reference: created.order_reference,
      subtotal: order.subtotal,
      discountRate: order.discountRate,
      discountAmount: order.discountAmount,
      itemCount: order.itemCount,
      deliveryFee: order.deliveryFee,
      total: order.total,
      currency: order.currency,
      whatsappNumber: business.whatsappNumber,
      message: "Your order has been received. We will contact you to confirm it.",
    });
  } catch (error) {
    // Log the real reason on the server only. The customer sees a friendly
    // message, because technical errors should never be exposed publicly.
    console.error("Order submission failed:", error);

    return NextResponse.json(
      {
        ok: false,
        message:
          "We could not save your order right now. Please try again, or contact us on WhatsApp and we will help you.",
      },
      { status: 500 }
    );
  }
}

